### ISSUE TITLE
Will this library and the SEER API support UICC 8 edition of TNM?

### ISSUE THREAD

**Issue by mgurley** [imsweb/staging-client-java#65]
If I am correct this library and SEER API currently output UNICC 7 edition TNM, correct?  For the NAACCR variables:

TNM CLIN T NAACCR 940
TNM CLIN N NAACCR 950
TNM CLIN M NAACCR 960

TNM PATH T NAACCR 880
TNM PATH N NAACCR 890
TNM PATH M NAACCR 900

Will this library and the SEER API support the UICC 8 edition of TNM?  If so, will it be bind the 8th edition only to the following variables:

AJCC TNM CLIN T NAACCR 1001
AJCC TNM CLIN N NAACCR 1002
AJCC TNM CLIN M NAACCR 1003

AJCC TNM PATH T NAACCR 1011
AJCC TNM PATH N NAACCR 1012
AJCC TNM PATH M NAACCR 1013

**Comment by ctmay4** [comment]
@schusslern can you please comment?

**Comment by schusslern** [comment]
Hello @mgurley 
at this time we h ave no plans to support the UICC 8th edition.  The AJCC TNM Clin and Path fields you mention (1001-1003, 1011-1013) would be used for AJCC 8th edition.  However, with licensing issues, you would need to contact AJCC for their API (which I believe functions differently than this one).

I do not believe UICC is allowed to license in the United States anymore, but I may have misunderstood the situation.

**Comment by mgurley** [comment]
@schusslern So does that mean the SEER sites will not be expected to code to a version 8 staging edition?  Or rather that SEER sites will not be capable of relying on the SEER API to obtain version 8 staging possible values and bindings to SEER schemas and need to obtain this information from AJCC or UICC?

**Comment by schusslern** [comment]
@mgurley - SEER registries are only required to capture AJCC TNM 8th if they receive an abstract that has the CoC Accredited flag = 1 (ANALYTIC abstract prepared at facility WITH CoC accreditation of its cancer program (Includes Class of Case codes 10-22)).  Since CoC hospitals are required to code the AJCC TNM 8th fields in this situation, this should not represent extra work for the SEER registries.

SEER registries are not required to capture AJCC TNM 8th edition fields from other sources; they are not required to transmit these fields to NCI SEER.

The SEER Staging API will provide the AJCC ID based on the Site, Histology, and if necessary, Behavior, Sex, Age, or Schema Discriminators.  

And as you mention, the public SEER Staging API does NOT include the valid values for T, N, M or the staging calculations for Stage Group for AJCC 8th edition.

**Comment by VECorwin** [comment]
Considering the potential differences between the AJCC/UICC 8 and SEER TNM codes, how are CoC accredited institutes supposed to stage the EOD library which has both Clin and Path TNM codes as input values?  Will this library accept AJCC8 codes, or is there an easy way to convert these values to their SEER equivelants?

**Comment by schusslern** [comment]
The SEER EOD library (2018+) will not have AJCC 8, UICC 8th or a SEER variant of T,N, and M codes. It has the EOD and Summary Stage codes.  There isn't a conversion to go from T, N and M codes into EOD; as far as i'm aware they have to be coded as separate data items (but you could verify with Ask a SEER Registrar).

I also wouldn't say it 'has both Clin and Path TNM codes as input values', although it is true that when coding EOD, one should be considering all information gained from clinical and pathological procedures.

**Comment by VECorwin** [comment]
The EodInput Enum from the EOD library has constants that map to both Clin and Path TNM values including the new T & N Suffix values.  My question is possibly a multi-part inquiry:

1.  Are these values really needed in order to properly stage the EOD library?

2.  Will the library accept the AJCC TNM values as inputs since the NAACCR standard does not appear to have a place for the SEER TNM codes?

**Comment by ctmay4** [comment]
Those values should not be there.  They are leftover from before the AJCC licensing issues.  

The following fields should not be there and will be removed in the next version.

```
CLIN_T("clin_t"),
CLIN_T_SUFFIX("clin_t_suffix"),
CLIN_N("clin_n"),
CLIN_N_SUFFIX("clin_n_suffix"),
CLIN_M("clin_m"),
CLIN_STAGE_GROUP_DIRECT("clin_stage_group_direct"),
PATH_T("path_t"),
PATH_T_SUFFIX("path_t_suffix"),
PATH_N("path_n"),
PATH_N_SUFFIX("path_n_suffix"),
PATH_M("path_m"),
PATH_STAGE_GROUP_DIRECT("path_stage_group_direct"),
YPATH_T("ypath_t"),
YPATH_T_SUFFIX("ypath_t_suffix"),
YPATH_N("ypath_n"),
YPATH_N_SUFFIX("ypath_n_suffix"),
YPATH_M("ypath_m"),
YPATH_STAGE_GROUP_DIRECT("ypath_stage_group_direct")
```

**Comment by ctmay4** [comment]
A new version of the staging-algorithm-eod-public (1.6.1) was just released that removed the unused inputs.  It will be available on Maven central in the next 30 minutes or so.
